# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed for Gaia.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f conda_env.yml

name: core3d-dev

channels:
- kitware-geospatial
- conda-forge
- defaults

dependencies:
- gdal
- pdal
- gaia
- pyproj
- scipy
- vtk
- six
- requests
- shapely
- pillow
- celery
- nodejs
- jsonschema
- geojson
- flake8
- pytest
