# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed for Danesfield.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f conda_env.yml
#
# then:
#
# source activate core3d-dev
# conda install -c kitware-geospatial core3d-tf_ops
# conda install -c conda-forge opencv
#
# For macs (that dont have nvidia GPUS) you don't execute the last step.

name: core3d-dev

channels:
- kitware-geospatial
- pytorch
- conda-forge
- defaults

dependencies:
- pubgeo-core3d-metrics
- gdal
- libgdal
- pdal
- python-pdal
- texture-atlas
- gaia
- pyproj
- scipy
- vtk
- jsonschema
- geojson
- flake8
- pytest
- pytorch
- shapely
- scikit-learn
- scikit-image
- liblas
- flann
- python-pcl
- pcl
- cgal
- xorg-libsm
- xorg-libX11
- core3d-purdue
- pip:
  - ubelt
  - plyfile
- torchvision
- tqdm
- matplotlib
