# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed for Danesfield.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f conda_env.yml
# then:
# source activate core3d-dev
# conda install -c kitware-danesfield -c kitware-danesfield-df core3d-tf_ops
# conda install -c kitware-danesfield-cf opencv
#
# The two extra steps are required because we use binary packages from
# different repos: conda-forge and defaults.
# The kitware-danesfield-pt, kitware-danesfield-cf and kitware-danesfield-df repos store
# private copies of packages from pytorch, conda-forge and defaults.
# For macs (that dont have nvidia GPUS) you don't execute the last two steps.

name: core3d-dev

channels:
- kitware-danesfield
- kitware-danesfield-pt
- kitware-danesfield-cf
- kitware-danesfield-df

dependencies:
- pubgeo-core3d-metrics
- gdal
- libgdal
- pdal
- python-pdal
- texture-atlas
- gaia
- pyproj
- scipy
- vtk
- jsonschema
- geojson
- flake8
- pytest
# Rutgers needs 0.4.*, we need cuda 9 and python 3.6
- cuda90
- pytorch=0.4.*
- shapely
- scikit-learn
- scikit-image
- liblas
- flann
- python-pcl
- pcl
- cgal
- xorg-libsm
- xorg-libX11
- core3d-purdue
- pip:
  - ubelt
  - plyfile
- torchvision
- tqdm
- matplotlib
- requests
